[package]
name = "tokio-postgres-rustls"
description = "Rustls integration for tokio-postgres"
version = "0.10.0"
authors = ["Jasper Hugo <jasper@jasperhugo.com>"]
repository = "https://github.com/jbg/tokio-postgres-rustls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
futures = { version = "0.3.29", default-features = false }
ring = { version = "0.17.7", default-features = false }
rustls = { version = "0.22.1", default-features = false }
tokio = { version = "1.35.1", default-features = false }
tokio-postgres = { version = "0.7.10", default-features = false }
tokio-rustls = { version = "0.25.0", default-features = false }

[dev-dependencies]
env_logger = { version = "0.10.1", default-features = false }
tokio = { version = "1.35.1", features = ["macros", "rt"] }
tokio-postgres = "0.7.10"
rustls = { version = "0.22.1", features = [] }
